import {
Atom,
BookOpenCheck,
Castle,
Dna,
FileQuestion,
Flag,
Flame,
FlaskConical,
Globe,
Landmark,
Scale,
Shuffle,
TrendingUp,
Zap,
type LucideIcon
} from "lucide-react";
export const PRIORITY_BADGE_STYLE: Record<string, { label: string; badgeBg: string; badgeColor: string }> = {
  Core: { label: "Core", badgeBg: "rgba(0, 113, 227, 0.12)", badgeColor: "var(--mac-blue, #0071e3)" },
  "Very High": { label: "Very High", badgeBg: "rgba(0, 113, 227, 0.12)", badgeColor: "var(--mac-blue, #0071e3)" },
  High: { label: "High", badgeBg: "rgba(16, 185, 129, 0.12)", badgeColor: "#059669" },
  Medium: { label: "Medium", badgeBg: "rgba(245, 158, 11, 0.12)", badgeColor: "#d97706" },
  Lower: { label: "Lower", badgeBg: "rgba(100, 116, 139, 0.12)", badgeColor: "#64748b" },
};

export type Priority = "very-high" | "high" | "medium" | "low" | "least";

export interface Topic {
  id: number;
  name: string;
  slug: string;
  subtopics: string[];
  priority: Priority;
  questions: string;
  icon: LucideIcon;
  color: string;
  description: string;
  expectedMarks: string;
}

export const TOPICS: Topic[] = [
  {
    id: 1,
    priority: "very-high",
    icon: Landmark,
    color: "#f59e0b",
    name: "Ancient History",
    slug: "ancient-history",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Ancient civilizations, religious movements, empires, literature, art, architecture, education, and science.",
    subtopics: [
      "Jainism & Buddhism",
      "Mauryan Empire",
      "Indus Valley Civilization",
      "Gupta Empire",
      "Vedic Age",
      "Ancient Indian Art & Science",
    ],
  },
  {
    id: 2,
    priority: "very-high",
    icon: Castle,
    color: "#8b5cf6",
    name: "Medieval History",
    slug: "medieval-history",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Delhi Sultanate, Mughal rule, regional kingdoms, religious movements, administration, art, and architecture.",
    subtopics: [
      "Mughal Empire",
      "Delhi Sultanate",
      "Bhakti & Sufi Movements",
      "Marathas & Shivaji",
      "Vijayanagara & Bahmani Kingdoms",
      "Sikh Gurus & Khalsa",
    ],
  },
  {
    id: 3,
    priority: "very-high",
    icon: Flag,
    color: "#2563eb",
    name: "Modern History",
    slug: "modern-history",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "British expansion, constitutional development, social reform, national movements, and the freedom struggle.",
    subtopics: [
      "Gandhian Era",
      "Indian National Congress",
      "British Conquest & Expansion",
      "Governor-Generals & Viceroys",
      "Revolt of 1857",
      "Final Phase of Freedom Struggle",
    ],
  },
  {
    id: 4,
    priority: "very-high",
    icon: Scale,
    color: "#3b82f6",
    name: "Polity & Constitution",
    slug: "polity",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Constitutional articles, fundamental rights and duties, parliamentary procedures, judiciary powers, emergency provisions, and key amendments.",
    subtopics: [
      "Preamble & Constitutional Sources",
      "Fundamental Rights (Art 12-35) & Duties",
      "President, Prime Minister & Council",
      "Parliament (Lok Sabha / Rajya Sabha)",
      "Supreme Court & High Courts",
      "Constitutional Bodies & Amendments",
    ],
  },
  {
    id: 5,
    priority: "very-high",
    icon: Globe,
    color: "#10b981",
    name: "Geography",
    slug: "geography",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Physical geography, Indian river systems, mountain ranges, monsoon climate, mineral resources, agriculture, and global landforms.",
    subtopics: [
      "Indian Rivers & Drainage Basins",
      "Himalayan & Peninsular Mountains",
      "Climate, Monsoons & Soil Types",
      "Agriculture, Crops & Minerals",
      "National Parks & Biosphere Reserves",
      "World Continents, Straits & Oceans",
    ],
  },
  {
    id: 6,
    priority: "very-high",
    icon: Atom,
    color: "#0284c7",
    name: "Physics",
    slug: "physics",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Measurements, mechanics, heat, sound, light, electricity, magnetism, fluids, machines, energy, electronics, and atomic physics.",
    subtopics: [
      "Units & Measurements",
      "Motion & Force",
      "Work, Energy & Power",
      "Heat, Sound & Light",
      "Electricity & Magnetism",
      "Atomic & Nuclear Physics",
    ],
  },
  {
    id: 7,
    priority: "very-high",
    icon: FlaskConical,
    color: "#0891b2",
    name: "Chemistry",
    slug: "chemistry",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Matter, atoms, periodic classification, reactions, bonding, acids, metals, carbon, electrochemistry, fuels, and everyday chemistry.",
    subtopics: [
      "Matter & Atomic Structure",
      "Periodic Table",
      "Acids, Bases & Salts",
      "Metals & Non-Metals",
      "Chemical Reactions",
      "Carbon & Its Compounds",
    ],
  },
  {
    id: 8,
    priority: "very-high",
    icon: Dna,
    color: "#059669",
    name: "Biology",
    slug: "biology",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Human systems, diseases, nutrition, cells, genetics, plant and animal life, reproduction, ecology, evolution, and biotechnology.",
    subtopics: [
      "Human Body Systems",
      "Diseases & Immunity",
      "Nutrition & Vitamins",
      "Cell & Genetics",
      "Plant Physiology",
      "Ecology & Evolution",
    ],
  },
  {
    id: 9,
    priority: "high",
    icon: TrendingUp,
    color: "#8b5cf6",
    name: "Economy",
    slug: "economy",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Indian economic framework, GDP/GNP concepts, Union Budget, RBI monetary policies, inflation indices, banking terms, and government schemes.",
    subtopics: [
      "National Income, GDP & Per Capita",
      "Union Budget & Direct/Indirect Taxes",
      "RBI Monetary Policy & Repo Rates",
      "Inflation (CPI, WPI) & Market Types",
      "Five Year Plans & NITI Aayog",
      "Flagship Government Schemes",
    ],
  },
  {
    id: 10,
    priority: "high",
    icon: Flame,
    color: "#f43f5e",
    name: "Current Affairs",
    slug: "current-affairs",
    questions: "4-5",
    expectedMarks: "8-10 Marks",
    description: "Last 12 months of national and international news, sports championships, summits, awards, key appointments, and government indexes.",
    subtopics: [
      "National & International Summits",
      "Sports Tournaments & Olympic/Cricket News",
      "Nobel Prizes, Padma & National Awards",
      "Global Indices & India's Rankings",
      "Appointments, Resignations & Obits",
      "Government Portals & Treaties",
    ],
  },
  {
    id: 11,
    priority: "high",
    icon: BookOpenCheck,
    color: "#ec4899",
    name: "Static GK",
    slug: "static-gk",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Classical and folk dances, cultural festivals, heritage sites, national symbols, first in India/World, famous books, and global organizations.",
    subtopics: [
      "Classical & Folk Dances of Indian States",
      "Festivals & Cultural Heritage Fairs",
      "UNESCO World Heritage Sites & Temples",
      "First in India & World (Male/Female)",
      "Important National/International Days",
      "Famous Books, Authors & Headquarters",
    ],
  },
];

export const PRACTICE_MODES = [
  {
    key: "concept",
    title: "PYQ",
    sub: "Previous year Qs",
    mode: "concept",
    icon: FileQuestion,
    color: "#0d9488",
    gradient: "linear-gradient(135deg, #e6f7f2 0%, #d4f3eb 100%)",
    gradientDark: "linear-gradient(135deg, rgba(13, 148, 136, 0.2) 0%, rgba(13, 148, 136, 0.08) 100%)",
    border: "rgba(13, 148, 136, 0.22)",
    borderDark: "rgba(13, 148, 136, 0.35)",
    shadow: "0 2px 8px rgba(13, 148, 136, 0.08)",
  },
  {
    key: "formula",
    title: "CareerWill",
    sub: "Core facts & dates",
    mode: "formula",
    icon: BookOpenCheck,
    color: "#2563eb",
    gradient: "linear-gradient(135deg, #edf4fe 0%, #dbeafe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(37, 99, 235, 0.2) 0%, rgba(37, 99, 235, 0.08) 100%)",
    border: "rgba(37, 99, 235, 0.22)",
    borderDark: "rgba(37, 99, 235, 0.35)",
    shadow: "0 2px 8px rgba(37, 99, 235, 0.08)",
  },
  {
    key: "mixed",
    title: "PW",
    sub: "Comprehensive mixture",
    mode: "mixed",
    icon: Shuffle,
    color: "#4f46e5",
    gradient: "linear-gradient(135deg, #f1f3fd 0%, #e0e7ff 100%)",
    gradientDark: "linear-gradient(135deg, rgba(79, 70, 229, 0.2) 0%, rgba(79, 70, 229, 0.08) 100%)",
    border: "rgba(79, 70, 229, 0.22)",
    borderDark: "rgba(79, 70, 229, 0.35)",
    shadow: "0 2px 8px rgba(79, 70, 229, 0.08)",
  },
  {
    key: "ai-challenge",
    title: "Selection Way",
    sub: "Speed test",
    mode: "ai-challenge",
    icon: Zap,
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #f7f2fe 0%, #ede9fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(124, 58, 237, 0.2) 0%, rgba(124, 58, 237, 0.08) 100%)",
    border: "rgba(124, 58, 237, 0.22)",
    borderDark: "rgba(124, 58, 237, 0.35)",
    shadow: "0 2px 8px rgba(124, 58, 237, 0.08)",
  },
  {
    key: "easy",
    title: "Topic Mix",
    sub: "Foundation easy",
    mode: "easy",
    icon: Globe,
    color: "#0284c7",
    gradient: "linear-gradient(135deg, #edf9ff 0%, #e0f2fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(2, 132, 199, 0.2) 0%, rgba(2, 132, 199, 0.08) 100%)",
    border: "rgba(2, 132, 199, 0.22)",
    borderDark: "rgba(2, 132, 199, 0.35)",
    shadow: "0 2px 8px rgba(2, 132, 199, 0.08)",
  },
  {
    key: "hard",
    title: "Tier 2",
    sub: "Advanced level",
    mode: "hard",
    icon: Flame,
    color: "#e11d48",
    gradient: "linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)",
    gradientDark: "linear-gradient(135deg, rgba(225, 29, 72, 0.2) 0%, rgba(225, 29, 72, 0.08) 100%)",
    border: "rgba(225, 29, 72, 0.22)",
    borderDark: "rgba(225, 29, 72, 0.35)",
    shadow: "0 2px 8px rgba(225, 29, 72, 0.08)",
  },
] as const;