import {
  Percent,
  Divide,
  TrendingUp,
  Landmark,
  Clock,
  Gauge,
  Variable,
  Compass,
  Box,
  Orbit,
  Hash,
  BarChart3,
  Tag,
  FlaskConical,
  Users2,
  Radical,
  PieChart,
  Zap,
  CircleDot,
  Filter,
  FileQuestion,
  BookOpenCheck,
  Shuffle,
  Flame,
  type LucideIcon,
} from "lucide-react";

// ── Types ─────────────────────────────────────────────────────────────────────
export type Priority = "very-high" | "high" | "medium" | "low" | "least";

export interface Topic {
  id: number;
  name: string;
  slug: string;
  routeBase: string;
  subtopics: string[];
  priority: Priority;
  questions: string;
  icon: LucideIcon;
  color: string;
  description: string;
  expectedMarks: string;
}

// ── 17 SSC Mathematics Topics with Distinctly Colored SVG Icons ───────────────
export const TOPICS: Topic[] = [
  {
    id: 1,
    priority: "very-high",
    icon: Percent,
    color: "#38bdf8",
    name: "Percentages",
    slug: "percentages",
    routeBase: "/mathematics/arithmetic/percentages",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Fraction-to-percent conversions, percentage increase/decrease, successive percentage changes, and price-consumption balance.",
    subtopics: ["Percentage Change", "Successive Change", "Price & Consumption", "Population & Depreciation", "Exam Marks Logic"],
  },
  {
    id: 2,
    priority: "very-high",
    icon: Divide,
    color: "#a855f7",
    name: "Ratio & Proportion",
    slug: "ratio-and-proportion",
    routeBase: "/mathematics/arithmetic/ratio-and-proportion",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Fundamental ratios, compound ratios, third/fourth proportion, mean proportional, and coin-denomination distributions.",
    subtopics: ["Mean & Third Proportional", "Part-to-Whole Division", "Coins & Denominations", "Income & Expenditure", "Ages Problems"],
  },
  {
    id: 3,
    priority: "very-high",
    icon: TrendingUp,
    color: "#10b981",
    name: "Profit & Loss",
    slug: "profit-and-loss",
    routeBase: "/mathematics/arithmetic/profit-and-loss",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Cost price, selling price, profit/loss percentages, dishonest dealer tricks, marked price, and successive transactions.",
    subtopics: ["CP & SP Calculations", "Dishonest Dealer", "Successive Transactions", "Marked Price & Discount", "Faulty Weights"],
  },
  {
    id: 4,
    priority: "very-high",
    icon: Landmark,
    color: "#f59e0b",
    name: "Simple & Compound Interest",
    slug: "interest",
    routeBase: "/mathematics/arithmetic/interest",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Simple interest formulas, compounding periods (half-yearly/quarterly), effective rate of interest, and CI-SI difference tricks.",
    subtopics: ["SI Basic Formulas", "CI Half-Yearly & Quarterly", "Difference between CI & SI (2 & 3 Yrs)", "Installments Logic"],
  },
  {
    id: 5,
    priority: "very-high",
    icon: Clock,
    color: "#6366f1",
    name: "Time & Work",
    slug: "time-and-work",
    routeBase: "/mathematics/arithmetic/time-and-work",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Individual and group work efficiencies, LCM efficiency method, alternate day work schedules, and pipe filling/emptying.",
    subtopics: ["LCM Efficiency Method", "Pipes & Cisterns", "Wages & Earnings", "Alternate Days Working", "Men-Women-Boys Efficiency Equivalence"],
  },
  {
    id: 6,
    priority: "very-high",
    icon: Gauge,
    color: "#ec4899",
    name: "Time, Speed & Distance",
    slug: "time-and-distance",
    routeBase: "/mathematics/arithmetic/time-and-distance",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Relative speed, trains crossing poles/platforms, upstream-downstream boat speeds, circular tracks, and race dynamics.",
    subtopics: ["Average & Relative Speed", "Train Platform & Pole Crossing", "Boats & Streams (Upstream/Downstream)", "Linear & Circular Races"],
  },
  {
    id: 7,
    priority: "very-high",
    icon: Variable,
    color: "#f43f5e",
    name: "Algebra",
    slug: "algebra",
    routeBase: "/mathematics/algebra",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Polynomial identities, symmetric systems, quadratic equations, discriminant properties, and maximum/minimum values.",
    subtopics: ["Symmetric Polynomial Identities", "x + 1/x Family Values", "Quadratic Roots & Discriminant", "Component-Dividendo (C&D)", "Linear Equations & Graphs"],
  },
  {
    id: 8,
    priority: "very-high",
    icon: Compass,
    color: "#8b5cf6",
    name: "Geometry",
    slug: "geometry",
    routeBase: "/mathematics/geometry",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Triangle centers (incenter, circumcenter, orthocenter, centroid), circle tangent theorems, cyclic quadrilaterals, and similarity.",
    subtopics: ["Triangle Congruence & Similarity", "Centers of Triangle", "Circle Tangent & Secant Theorems", "Cyclic Quadrilateral Rules", "Chords & Arc Properties"],
  },
  {
    id: 9,
    priority: "very-high",
    icon: Box,
    color: "#14b8a6",
    name: "Mensuration 2D & 3D",
    slug: "mensuration",
    routeBase: "/mathematics/mensuration",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "2D area/perimeter formulas, 3D surface area and volume of spheres, cones, cylinders, prisms, pyramids, and frustums.",
    subtopics: ["2D Polygons Area & Perimeter", "Cylinder, Cone & Sphere Volume", "Prisms & Pyramids", "Frustum of Cone", "Cutting & Melting of 3D Solids"],
  },
  {
    id: 10,
    priority: "very-high",
    icon: Orbit,
    color: "#06b6d4",
    name: "Trigonometry",
    slug: "trigonometry",
    routeBase: "/mathematics/trigonometry",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Standard angle values, complementary angles, trigonometric identities, maximum/minimum values, and heights and distances.",
    subtopics: ["Fundamental Identities", "Heights & Distances (Angle of Elevation)", "Complementary Angles Transformation", "Value Substitution Methods", "Min/Max of Trig Functions"],
  },
  {
    id: 11,
    priority: "high",
    icon: Hash,
    color: "#eab308",
    name: "Number System",
    slug: "number-system",
    routeBase: "/mathematics/number-system",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Divisibility rules, unit digit calculation, remainder theorems (Wilson, Fermat, Euler), factors count, and trailing zeros.",
    subtopics: ["Divisibility Rules (7, 11, 13, 72, 88)", "Unit Digit & Cyclicity", "Remainders Theorems", "Number of Factors & Sum", "LCM & HCF Advanced Word Problems"],
  },
  {
    id: 12,
    priority: "high",
    icon: BarChart3,
    color: "#84cc16",
    name: "Averages",
    slug: "averages",
    routeBase: "/mathematics/arithmetic/averages",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Arithmetic mean, deviation method for weighted averages, batting/bowling averages, and group replacement/addition.",
    subtopics: ["Weighted Average & Deviation", "Batting & Bowling Averages", "Inclusion & Exclusion from Group", "Error Correction in Data Sets"],
  },
  {
    id: 13,
    priority: "high",
    icon: Tag,
    color: "#f97316",
    name: "Discount",
    slug: "discount",
    routeBase: "/mathematics/arithmetic/discount",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Single equivalent discount, successive discounts, marked price markups, and Buy X Get Y Free promotion economics.",
    subtopics: ["Successive Discount Formula", "Buy X Get Y Free Schemes", "Relationship between CP, MP and Discount", "Markup Percentage vs Profit Percentage"],
  },
  {
    id: 14,
    priority: "medium",
    icon: FlaskConical,
    color: "#0ea5e9",
    name: "Mixture & Alligation",
    slug: "mixture-and-alligation",
    routeBase: "/mathematics/arithmetic/mixture-and-alligation",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Alligation cross-rule, combining solutions of different concentrations, repeated liquid replacement, and price mixing.",
    subtopics: ["Alligation Rule Matrix", "Concentration & Dilution", "Repeated Liquid Replacement", "Average Cost of Blends", "Multi-Liquid Mixtures"],
  },
  {
    id: 15,
    priority: "medium",
    icon: Users2,
    color: "#d946ef",
    name: "Partnership",
    slug: "partnership",
    routeBase: "/mathematics/arithmetic/partnership",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Capital investment ratios, time-weighted capital contributions, active vs sleeping partner allowances, and profit shares.",
    subtopics: ["Simple Investment Ratio", "Time-Weighted Capital Ratio", "Working Partner Salary", "Joining & Leaving Mid-Year"],
  },
  {
    id: 16,
    priority: "medium",
    icon: Radical,
    color: "#22d3ee",
    name: "Square Roots & Surds",
    slug: "square-roots",
    routeBase: "/mathematics/arithmetic/square-roots",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Finding square roots and cube roots, surd simplification, rationalizing denominators, and radical algebra.",
    subtopics: ["Perfect Squares & Cubes", "Rationalizing the Denominator", "Simplification of Surds", "Nested Square Roots"],
  },
  {
    id: 17,
    priority: "medium",
    icon: PieChart,
    color: "#fb7185",
    name: "Statistics & Probability",
    slug: "statistics-probability",
    routeBase: "/mathematics/statistics-probability",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Mean, median, mode, standard deviation, variance, coefficient of variation, simple event probability, and DI charts.",
    subtopics: ["Mean, Median & Mode Formula", "Variance & Standard Deviation", "Classical Probability & Dice/Cards", "Bar Charts & Pie Charts Interpretation"],
  },
];

// ── Priority Visual Config ───────────────────────────────────────────────────
export const PRIORITY_CONFIG: Record<
  Priority,
  { label: string; badgeBg: string; badgeColor: string }
> = {
  "very-high": {
    label: "Core",
    badgeBg: "rgba(0, 113, 227, 0.1)",
    badgeColor: "var(--mac-blue)",
  },
  high: {
    label: "High",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-primary)",
  },
  medium: {
    label: "Medium",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-secondary)",
  },
  low: {
    label: "Low",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-secondary)",
  },
  least: {
    label: "Least",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-tertiary)",
  },
};

export const CATEGORIES = [
  { id: "very-high", label: "Core", icon: Zap },
  { id: "high", label: "High", icon: TrendingUp },
  { id: "medium", label: "Medium", icon: CircleDot },
  { id: "low", label: "Low", icon: Filter },
] as const;

export type CategoryId = typeof CATEGORIES[number]["id"];

export const PRACTICE_MODES = [
  {
    key: "concept",
    title: "PYQ",
    sub: "Previous year Qs",
    mode: "concept",
    icon: FileQuestion,
    color: "#0d9488",
    gradient: "linear-gradient(135deg, #e6f7f2 0%, #d4f3eb 100%)",
    gradientDark: "linear-gradient(135deg, rgba(13, 148, 136, 0.2) 0%, rgba(13, 148, 136, 0.08) 100%)",
    border: "rgba(13, 148, 136, 0.22)",
    borderDark: "rgba(13, 148, 136, 0.35)",
    shadow: "0 2px 8px rgba(13, 148, 136, 0.08)",
  },
  {
    key: "formula",
    title: "CareerWill",
    sub: "Formulas & rules",
    mode: "formula",
    icon: BookOpenCheck,
    color: "#2563eb",
    gradient: "linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(37, 99, 235, 0.2) 0%, rgba(37, 99, 235, 0.08) 100%)",
    border: "rgba(37, 99, 235, 0.22)",
    borderDark: "rgba(37, 99, 235, 0.35)",
    shadow: "0 2px 8px rgba(37, 99, 235, 0.08)",
  },
  {
    key: "mixed",
    title: "PW",
    sub: "Full mix practice",
    mode: "mixed",
    icon: Shuffle,
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #f5f3ff 0%, #ede9fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(124, 58, 237, 0.2) 0%, rgba(124, 58, 237, 0.08) 100%)",
    border: "rgba(124, 58, 237, 0.22)",
    borderDark: "rgba(124, 58, 237, 0.35)",
    shadow: "0 2px 8px rgba(124, 58, 237, 0.08)",
  },
  {
    key: "ai-challenge",
    title: "Selection Way",
    sub: "Speed test & traps",
    mode: "ai-challenge",
    icon: Zap,
    color: "#d97706",
    gradient: "linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%)",
    gradientDark: "linear-gradient(135deg, rgba(217, 119, 6, 0.2) 0%, rgba(217, 119, 6, 0.08) 100%)",
    border: "rgba(217, 119, 6, 0.22)",
    borderDark: "rgba(217, 119, 6, 0.35)",
    shadow: "0 2px 8px rgba(217, 119, 6, 0.08)",
  },
  {
    key: "easy",
    title: "Topic Mix",
    sub: "Foundation easy",
    mode: "easy",
    icon: Compass,
    color: "#0284c7",
    gradient: "linear-gradient(135deg, #edf9ff 0%, #e0f2fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(2, 132, 199, 0.2) 0%, rgba(2, 132, 199, 0.08) 100%)",
    border: "rgba(2, 132, 199, 0.22)",
    borderDark: "rgba(2, 132, 199, 0.35)",
    shadow: "0 2px 8px rgba(2, 132, 199, 0.08)",
  },
  {
    key: "hard",
    title: "Tier 2",
    sub: "Advanced level",
    mode: "hard",
    icon: Flame,
    color: "#e11d48",
    gradient: "linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)",
    gradientDark: "linear-gradient(135deg, rgba(225, 29, 72, 0.2) 0%, rgba(225, 29, 72, 0.08) 100%)",
    border: "rgba(225, 29, 72, 0.22)",
    borderDark: "rgba(225, 29, 72, 0.35)",
    shadow: "0 2px 8px rgba(225, 29, 72, 0.08)",
  },
] as const;
