import {
AlignLeft,
ArrowLeftRight,
BookMarked,
BookOpenCheck,
CheckSquare,
CircleDot,
Clock,
Edit3,
FileQuestion,
FileSpreadsheet,
FileText,
Filter,
Flame,
Layout,
Link2,
MessageCircle,
MessageSquare,
Navigation,
Newspaper,
Puzzle,
RefreshCw,
Scale,
Search,
Shuffle,
SpellCheck,
Target,
TrendingUp,
UserCheck,
Volume2,
Zap,
type LucideIcon
} from "lucide-react";
export type Priority = "very-high" | "high" | "medium" | "low" | "least";

export interface Topic {
  id: number;
  name: string;
  slug: string;
  subtopics: string[];
  priority: Priority;
  questions: string;
  icon: LucideIcon;
  color: string;
  description: string;
  expectedMarks: string;
}

export const TOPICS: Topic[] = [
  {
    id: 1,
    priority: "very-high",
    icon: ArrowLeftRight,
    color: "#38bdf8",
    name: "Synonyms & Antonyms",
    slug: "synonyms-antonyms",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Vocabulary mastery testing exact synonyms, opposite nuances, contextual meanings, and degrees of connotation.",
    subtopics: ["Synonym Selection", "Antonym Selection", "Contextual Usage", "Degree of Meaning", "Root Word Etymology"],
  },
  {
    id: 2,
    priority: "very-high",
    icon: BookMarked,
    color: "#a855f7",
    name: "One Word Substitution",
    slug: "one-word-substitution",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Concise vocabulary replacing phrases for professions, places, medical terms, philosophies, and behavior patterns.",
    subtopics: ["People & Professions", "Places & Institutions", "Phobias & Manias", "Sciences & Disciplines", "Government Terms"],
  },
  {
    id: 3,
    priority: "very-high",
    icon: MessageSquare,
    color: "#f59e0b",
    name: "Idioms & Phrases",
    slug: "idioms-phrases",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Figurative expressions, historical idioms, phrasal verbs, and contextual sentence placement.",
    subtopics: ["Meaning Identification", "Correct Usage in Sentences", "Fill with Idiom", "Origin & Context", "Color & Animal Idioms"],
  },
  {
    id: 4,
    priority: "very-high",
    icon: Search,
    color: "#ef4444",
    name: "Spot the Error",
    slug: "spot-the-error-error-detection",
    questions: "4-5",
    expectedMarks: "8-10 Marks",
    description: "Locating grammatical flaws, tense mismatches, subject-verb disagreements, and incorrect modifiers across sentence parts.",
    subtopics: ["Subject-Verb Inversion", "Tense Inconsistency", "Preposition Errors", "Pronoun Reference Flaws", "Part-wise Detection"],
  },
  {
    id: 5,
    priority: "very-high",
    icon: Edit3,
    color: "#10b981",
    name: "Sentence Improvement",
    slug: "sentence-correction-improvement",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Enhancing grammatical accuracy, conciseness, and stylistic flow by replacing underlined phrases.",
    subtopics: ["Replace Underlined Part", "Verb Tense Correction", "No Improvement Cases", "Idiomatic Precision", "Redundancy Elimination"],
  },
  {
    id: 6,
    priority: "very-high",
    icon: FileSpreadsheet,
    color: "#6366f1",
    name: "Cloze Test",
    slug: "cloze-test",
    questions: "5",
    expectedMarks: "10 Marks",
    description: "Contextual paragraph comprehension requiring grammar and vocabulary completions for missing blanks.",
    subtopics: ["Grammar Cloze", "Vocabulary Cloze", "Collocation Blanks", "Discourse Transition", "Contextual Inference"],
  },
  {
    id: 7,
    priority: "very-high",
    icon: Newspaper,
    color: "#06b6d4",
    name: "Reading Comprehension",
    slug: "reading-comprehension",
    questions: "5-10",
    expectedMarks: "10-20 Marks",
    description: "Extracting main themes, author's tone, factual details, inferential deductions, and contextual word definitions.",
    subtopics: ["Central Theme / Title", "Inference & Deduction", "Author Tone & Attitude", "Direct Fact Retrieval", "Contextual Vocab"],
  },
  {
    id: 8,
    priority: "high",
    icon: RefreshCw,
    color: "#f97316",
    name: "Active & Passive Voice",
    slug: "active-passive-voice",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Voice conversions across all 12 tenses, modal auxiliaries, interrogative structures, and imperative commands.",
    subtopics: ["Simple & Perfect Tenses", "Modal Verbs (Can/Must/Should)", "Interrogatives & 'Wh-' Questions", "Imperative Commands", "Prepositional Passive"],
  },
  {
    id: 9,
    priority: "high",
    icon: MessageCircle,
    color: "#8b5cf6",
    name: "Direct & Indirect Narration",
    slug: "direct-indirect-narration",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Reported speech transformations including tense backshifts, pronoun shifts, time-place changes, and exclamatory sentences.",
    subtopics: ["Assertive Statements", "Interrogative 'If/Whether'", "Imperative Orders & Requests", "Exclamations & Wishes", "Universal Truth Exceptions"],
  },
  {
    id: 10,
    priority: "high",
    icon: Clock,
    color: "#ec4899",
    name: "Tenses",
    slug: "tenses",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Timeline consistency, present perfect vs simple past, conditional clauses (If/When), and future time expressions.",
    subtopics: ["Present Perfect vs Simple Past", "Past Perfect Sequences", "Conditional Clauses (Type 1, 2, 3)", "Since/For Time Markers", "Continuous vs Stative Verbs"],
  },
  {
    id: 11,
    priority: "high",
    icon: Scale,
    color: "#3b82f6",
    name: "Subject-Verb Agreement",
    slug: "subject-verb-agreement",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Syntactic agreement rules with collective nouns, correlative pairs (Either/Or), indefinite pronouns, and inverted sentences.",
    subtopics: ["Either...Or / Neither...Nor", "Collective Nouns Plurality", "Intervening Prepositional Phrases", "Each / Every / None", "Inverted Verb Placement"],
  },
  {
    id: 12,
    priority: "high",
    icon: Shuffle,
    color: "#eab308",
    name: "Para-Jumbles",
    slug: "para-jumbles",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Logical reordering of shuffled sentences using opening identifiers, pronoun antecedents, and connecting transition words.",
    subtopics: ["Identifying Opening Sentence", "Pronoun Reference Links", "Chronological Flow", "Cause & Effect Connectors", "Concluding Summary"],
  },
  {
    id: 13,
    priority: "high",
    icon: Puzzle,
    color: "#14b8a6",
    name: "Fill in the Blanks",
    slug: "fill-in-the-blanks",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Sentence completions evaluating grammatical prepositions, verb agreements, and precise vocabulary nuances.",
    subtopics: ["Single Blank Grammar", "Double Blanks Logic", "Prepositional Collocations", "Vocabulary Precision", "Contextual Contrast"],
  },
  {
    id: 14,
    priority: "medium",
    icon: SpellCheck,
    color: "#d946ef",
    name: "Spelling & Misspelled Words",
    slug: "spelling-misspelled-words",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Identifying correctly or incorrectly spelled words with tricky double consonants, silent letters, and suffix additions.",
    subtopics: ["Double Consonant Words", "Silent Letter Words", "'-ible' vs '-able' Suffixes", "Commonly Confused Spellings", "Detect Incorrect Word"],
  },
  {
    id: 15,
    priority: "medium",
    icon: Navigation,
    color: "#06b6d4",
    name: "Prepositions",
    slug: "prepositions",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Fixed prepositions, directional movement, temporal indicators (In/On/At), and idiomatic phrasal preposition combinations.",
    subtopics: ["Fixed Preposition Rules", "Prepositions of Time & Place", "Movement & Direction (Into/Onto)", "Phrasal Prepositions", "Verbs without Prepositions"],
  },
  {
    id: 16,
    priority: "medium",
    icon: FileText,
    color: "#84cc16",
    name: "Articles",
    slug: "articles",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Indefinite articles (A/An) phonetic rules, definite article (The) usage with geographical/proper nouns, and zero article omissions.",
    subtopics: ["Vowel Sound Rules (A/An)", "Definite Article 'The' Usage", "Zero Article Omissions", "Articles with Superlatives", "Generic vs Specific Reference"],
  },
  {
    id: 17,
    priority: "medium",
    icon: Link2,
    color: "#f43f5e",
    name: "Conjunctions",
    slug: "conjunctions",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Coordinating conjunctions (FANBOYS), subordinating clauses, correlative pairs (Not only...but also), and conjunctive adverbs.",
    subtopics: ["Correlative Conjunction Pairs", "Lest...Should Rules", "No sooner...than / Hardly...when", "Although / Even Though Contrast", "Subordinating Clauses"],
  },
  {
    id: 18,
    priority: "medium",
    icon: Volume2,
    color: "#22d3ee",
    name: "Homonyms & Homophones",
    slug: "homonyms-homophones",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Differentiating words with identical pronunciation or spelling but divergent meanings, origins, and usages.",
    subtopics: ["Same Sound Different Spelling", "Same Spelling Different Meaning", "Contextual Selection", "Easily Confused Pairs"],
  },
  {
    id: 19,
    priority: "medium",
    icon: Layout,
    color: "#a855f7",
    name: "Sentence Structure & Clauses",
    slug: "sentence-structure",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Analyzing simple, compound, and complex sentences; identifying relative clauses; and transforming sentence clauses.",
    subtopics: ["Simple, Compound, Complex", "Noun & Adverb Clauses", "Relative Pronoun Clauses", "Transformation of Sentences", "Run-on Sentences & Fragments"],
  },
  {
    id: 20,
    priority: "low",
    icon: CheckSquare,
    color: "#10b981",
    name: "Para / Sentence Completion",
    slug: "para-sentence-completion",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Selecting the most logical opening, middle, or concluding sentence that sustains the author's tone and paragraph premise.",
    subtopics: ["Concluding Sentence Selection", "Opening Sentence Selection", "Tone & Flow Consistency", "Logical Deductions"],
  },
  {
    id: 21,
    priority: "low",
    icon: UserCheck,
    color: "#38bdf8",
    name: "Pronouns",
    slug: "pronouns",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Pronoun-antecedent agreement, subjective vs objective cases, reflexive vs emphatic pronouns, and relative pronouns.",
    subtopics: ["Subjective vs Objective Cases", "Reflexive & Emphatic Pronouns", "Relative Pronouns (Who/Whom/Which/That)", "Order of Pronouns (231 & 123)"],
  },
  {
    id: 22,
    priority: "low",
    icon: Target,
    color: "#fb7185",
    name: "Modifiers",
    slug: "modifiers",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Detecting and correcting misplaced modifiers, dangling participles, squinting modifiers, and adjective vs practical usages.",
    subtopics: ["Dangling Participles", "Misplaced Modifiers", "Adjective vs Adverb Choice", "Squinting Modifiers"],
  },
  {
    id: 23,
    priority: "low",
    icon: AlignLeft,
    color: "#f59e0b",
    name: "Parallelism",
    slug: "parallelism",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Ensuring parallel syntactic structures across series, comparisons with 'than'/'as', and correlative conjunction lists.",
    subtopics: ["Parallel Verb Forms", "Parallel Series & Lists", "Comparisons with 'Than' / 'As'", "Correlative Parallel Structures"],
  },
];

export const PRIORITY_CONFIG: Record<
  Priority,
  { label: string; badgeBg: string; badgeColor: string }
> = {
  "very-high": {
    label: "Core",
    badgeBg: "rgba(0, 113, 227, 0.1)",
    badgeColor: "var(--mac-blue)",
  },
  high: {
    label: "High",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-primary)",
  },
  medium: {
    label: "Medium",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-secondary)",
  },
  low: {
    label: "Low",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-secondary)",
  },
  least: {
    label: "Least",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-tertiary)",
  },
};

export const CATEGORIES = [
  { id: "very-high", label: "Core", icon: Zap },
  { id: "high", label: "High", icon: TrendingUp },
  { id: "medium", label: "Medium", icon: CircleDot },
  { id: "low", label: "Low", icon: Filter },
] as const;

export type CategoryId = typeof CATEGORIES[number]["id"];

export const PRACTICE_MODES = [
  {
    key: "concept",
    title: "PYQ",
    sub: "Previous year Qs",
    mode: "concept",
    icon: FileQuestion,
    color: "#0d9488",
    gradient: "linear-gradient(135deg, #e6f7f2 0%, #d4f3eb 100%)",
    gradientDark: "linear-gradient(135deg, rgba(13, 148, 136, 0.2) 0%, rgba(13, 148, 136, 0.08) 100%)",
    border: "rgba(13, 148, 136, 0.22)",
    borderDark: "rgba(13, 148, 136, 0.35)",
    shadow: "0 2px 8px rgba(13, 148, 136, 0.08)",
  },
  {
    key: "formula",
    title: "CareerWill",
    sub: "Words & grammar rules",
    mode: "formula",
    icon: BookOpenCheck,
    color: "#2563eb",
    gradient: "linear-gradient(135deg, #edf4fe 0%, #dbeafe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(37, 99, 235, 0.2) 0%, rgba(37, 99, 235, 0.08) 100%)",
    border: "rgba(37, 99, 235, 0.22)",
    borderDark: "rgba(37, 99, 235, 0.35)",
    shadow: "0 2px 8px rgba(37, 99, 235, 0.08)",
  },
  {
    key: "mixed",
    title: "PW",
    sub: "Comprehensive mixture",
    mode: "mixed",
    icon: Shuffle,
    color: "#4f46e5",
    gradient: "linear-gradient(135deg, #f1f3fd 0%, #e0e7ff 100%)",
    gradientDark: "linear-gradient(135deg, rgba(79, 70, 229, 0.2) 0%, rgba(79, 70, 229, 0.08) 100%)",
    border: "rgba(79, 70, 229, 0.22)",
    borderDark: "rgba(79, 70, 229, 0.35)",
    shadow: "0 2px 8px rgba(79, 70, 229, 0.08)",
  },
  {
    key: "ai-challenge",
    title: "Selection Way",
    sub: "Speed test",
    mode: "ai-challenge",
    icon: Zap,
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #f7f2fe 0%, #ede9fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(124, 58, 237, 0.2) 0%, rgba(124, 58, 237, 0.08) 100%)",
    border: "rgba(124, 58, 237, 0.22)",
    borderDark: "rgba(124, 58, 237, 0.35)",
    shadow: "0 2px 8px rgba(124, 58, 237, 0.08)",
  },
  {
    key: "easy",
    title: "Topic Mix",
    sub: "Foundation easy",
    mode: "easy",
    icon: Navigation,
    color: "#0284c7",
    gradient: "linear-gradient(135deg, #edf9ff 0%, #e0f2fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(2, 132, 199, 0.2) 0%, rgba(2, 132, 199, 0.08) 100%)",
    border: "rgba(2, 132, 199, 0.22)",
    borderDark: "rgba(2, 132, 199, 0.35)",
    shadow: "0 2px 8px rgba(2, 132, 199, 0.08)",
  },
  {
    key: "hard",
    title: "Tier 2",
    sub: "Advanced level",
    mode: "hard",
    icon: Flame,
    color: "#e11d48",
    gradient: "linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)",
    gradientDark: "linear-gradient(135deg, rgba(225, 29, 72, 0.2) 0%, rgba(225, 29, 72, 0.08) 100%)",
    border: "rgba(225, 29, 72, 0.22)",
    borderDark: "rgba(225, 29, 72, 0.35)",
    shadow: "0 2px 8px rgba(225, 29, 72, 0.08)",
  },
] as const;

export const STUDY_MODE_TOPICS = new Set([
  "synonyms-antonyms",
  "one-word-substitution",
  "idioms-phrases",
  "spelling-misspelled-words",
  "homonyms-homophones",
]);