import {
ArrowLeftRight,
BookOpenCheck,
Box,
Brain,
Calculator,
CircleDot,
Compass,
FileCheck,
FileQuestion,
Filter,
Flame,
FlipHorizontal,
Heart,
HelpCircle,
Lock,
MessageSquareCode,
Puzzle,
Scale,
Scissors,
Shapes,
Share2,
Shuffle,
SpellCheck,
Swords,
Table2,
TrendingUp,
Trophy,
Type,
Users2,
Zap,
type LucideIcon
} from "lucide-react";
export type Priority = "very-high" | "high" | "medium" | "low" | "least";

export interface Topic {
  id: number;
  name: string;
  slug: string;
  subtopics: string[];
  priority: Priority;
  questions: string;
  icon: LucideIcon;
  color: string;
  description: string;
  expectedMarks: string;
}

export const TOPICS: Topic[] = [
  {
    id: 1,
    priority: "very-high",
    icon: Lock,
    color: "#007AFF",
    name: "Coding & Decoding",
    slug: "coding-decoding",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Pattern deciphering based on alphabetical shifts, reverse letters, numerical positions, and symbol operations.",
    subtopics: ["Letter Coding", "Number Coding", "Symbolic Coding", "Numerical Operations", "Mixed Coding"],
  },
  {
    id: 2,
    priority: "very-high",
    icon: MessageSquareCode,
    color: "#a855f7",
    name: "Syllogism & Inferences",
    slug: "syllogism-inferences",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Deductive reasoning testing validity of conclusions and possibilities from premise statements.",
    subtopics: ["Two Statement", "Three Statement", "Possibility Cases", "Drawing Inferences", "Either-Or Logic"],
  },
  {
    id: 3,
    priority: "very-high",
    icon: Puzzle,
    color: "#f59e0b",
    name: "Puzzle & Seating Arrangement",
    slug: "puzzle-seating-arrangement",
    questions: "3-4",
    expectedMarks: "6-8 Marks",
    description: "Constraint satisfaction problems involving linear, circular, floor, and multi-parameter arrangements.",
    subtopics: ["Linear Seating", "Circular Seating", "Floor Puzzle", "Box Puzzle", "Day/Month Puzzle"],
  },
  {
    id: 4,
    priority: "very-high",
    icon: TrendingUp,
    color: "#10b981",
    name: "Series",
    slug: "series",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Progressions based on arithmetic intervals, prime steps, letter gaps, and alternating logic.",
    subtopics: ["Number Series", "Letter Series", "Figural Series", "Alpha-Numeric Series", "Continuous Pattern"],
  },
  {
    id: 5,
    priority: "very-high",
    icon: ArrowLeftRight,
    color: "#ec4899",
    name: "Analogy",
    slug: "analogy",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Identifying underlying relationships between pairs of words, numbers, letters, or geometric shapes.",
    subtopics: ["Semantic Analogy", "Symbolic/Number Analogy", "Figural Analogy", "Word Analogy"],
  },
  {
    id: 6,
    priority: "very-high",
    icon: Filter,
    color: "#6366f1",
    name: "Classification (Odd One Out)",
    slug: "classification-odd-one-out",
    questions: "2-3",
    expectedMarks: "4-6 Marks",
    description: "Spotting anomalies among a set of entities using properties of squares, cubes, grammar, or semantics.",
    subtopics: ["Semantic Classification", "Figural Classification", "Symbolic Classification", "Number Based"],
  },
  {
    id: 7,
    priority: "high",
    icon: Users2,
    color: "#f43f5e",
    name: "Blood Relations",
    slug: "blood-relations",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Family tree decoding, generation leaps, gender deductions, and coded symbolic relations.",
    subtopics: ["Family Tree", "Coded Blood Relations", "Pointing to Photograph", "Statement Based"],
  },
  {
    id: 8,
    priority: "high",
    icon: Compass,
    color: "#06b6d4",
    name: "Direction & Distance",
    slug: "direction-distance",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Navigational trajectories, Pythagoras theorem applications, angle rotations, and shadow logic.",
    subtopics: ["Basic 8 Directions", "Distance Calculation", "Shadow Problems", "Space Orientation"],
  },
  {
    id: 9,
    priority: "high",
    icon: CircleDot,
    color: "#8b5cf6",
    name: "Venn Diagram",
    slug: "venn-diagram",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Set theory visualizations representing subsets, intersections, and multi-circle population counts.",
    subtopics: ["Relationship Diagrams", "Finding Elements", "Shaded Region", "3-Circle Venn"],
  },
  {
    id: 10,
    priority: "high",
    icon: Scale,
    color: "#f97316",
    name: "Inequalities",
    slug: "inequalities",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Comparing quantities using algebraic inequality symbols (<, >, ≤, ≥, =) and chain statements.",
    subtopics: ["Direct Inequalities", "Coded Inequalities", "Mathematical Inequalities", "Chain Statements"],
  },
  {
    id: 11,
    priority: "high",
    icon: Calculator,
    color: "#3b82f6",
    name: "Mathematical Operations",
    slug: "mathematical-symbolic-operations",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Evaluating expressions via BODMAS rule after swapping operators, digits, or symbolic substitutions.",
    subtopics: ["BODMAS Based", "Symbol Substitution", "Sign Interchange", "Numerical Operations"],
  },
  {
    id: 12,
    priority: "high",
    icon: Trophy,
    color: "#eab308",
    name: "Order & Ranking",
    slug: "order-ranking",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Determining rank, position from ends, total people in a row, and position interchange deductions.",
    subtopics: ["Position from Top/Bottom", "Rank in Row/Column", "Height/Weight Ordering", "Overlapping Positions"],
  },
  {
    id: 13,
    priority: "medium",
    icon: FileCheck,
    color: "#14b8a6",
    name: "Statement & Conclusion",
    slug: "statement-conclusion",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Determining whether a given conclusion logically follows strictly from the premise.",
    subtopics: ["Follows/Does Not Follow", "Implicit Conclusions", "Critical Thinking"],
  },
  {
    id: 14,
    priority: "medium",
    icon: HelpCircle,
    color: "#d946ef",
    name: "Statement & Assumptions",
    slug: "statement-assumptions",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Identifying unstated premises or implicit assumptions taken for granted before making a statement.",
    subtopics: ["Implicit Assumptions", "Explicit Assumptions", "Contextual Premises"],
  },
  {
    id: 15,
    priority: "medium",
    icon: Swords,
    color: "#ef4444",
    name: "Statement & Arguments",
    slug: "statement-arguments",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Evaluating whether proposed arguments are strong (logical, practical) or weak (biased, superficial).",
    subtopics: ["Strong/Weak Arguments", "Course of Action", "Cause & Effect"],
  },
  {
    id: 16,
    priority: "medium",
    icon: Brain,
    color: "#84cc16",
    name: "Critical Thinking",
    slug: "problem-solving-critical-thinking",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Multi-step contextual decision making, conditional rules, and applied logical inferences.",
    subtopics: ["Applied Logical Reasoning", "Step-based Problems", "Condition Based Logic"],
  },
  {
    id: 17,
    priority: "medium",
    icon: Shapes,
    color: "#0284c7",
    name: "Non-Verbal Figures",
    slug: "non-verbal-figures",
    questions: "1-2",
    expectedMarks: "2-4 Marks",
    description: "Visual pattern analysis including embedded figures, figure completion, and counting shapes.",
    subtopics: ["Embedded Figures", "Figure Completion", "Counting Figures", "Figural Pattern"],
  },
  {
    id: 18,
    priority: "medium",
    icon: Scissors,
    color: "#c026d3",
    name: "Paper Folding & Cutting",
    slug: "paper-folding-cutting",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Predicting symmetric hole patterns and punched cutouts upon unfolding folded sheets.",
    subtopics: ["Punched Hole", "Pattern Folding & Unfolding", "Symmetry Reflection"],
  },
  {
    id: 19,
    priority: "low",
    icon: FlipHorizontal,
    color: "#22d3ee",
    name: "Mirror & Water Image",
    slug: "mirror-water-image",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Lateral inversion (mirror image) and vertical inversion (water image) of alphanumeric strings and shapes.",
    subtopics: ["Letter/Number Mirror", "Clock Mirror Image", "Figural Mirror", "Water Image"],
  },
  {
    id: 20,
    priority: "low",
    icon: Box,
    color: "#f59e0b",
    name: "Cube & Dice",
    slug: "cube-dice",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Determining opposite faces from multiple rotations, unfolding standard/general dice, and painted cube cuts.",
    subtopics: ["Open/Closed Dice", "Face Opposite", "Cube Painting & Cutting", "3D Orientation"],
  },
  {
    id: 21,
    priority: "low",
    icon: Table2,
    color: "#10b981",
    name: "Matrix",
    slug: "matrix",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Row-column code lookups and missing numerical values calculated from horizontal/vertical logic.",
    subtopics: ["Missing Number/Letter", "Row-Column Coding", "Figure Matrix", "Grid Logic"],
  },
  {
    id: 22,
    priority: "low",
    icon: SpellCheck,
    color: "#6366f1",
    name: "Logical Sequence of Words",
    slug: "logical-sequence-of-words",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Arranging terms in chronological, functional, developmental, or dictionary alphabetical order.",
    subtopics: ["Dictionary Order", "Process/Hierarchy Order", "Word Building", "Natural Sequence"],
  },
  {
    id: 23,
    priority: "least",
    icon: Heart,
    color: "#fb7185",
    name: "Emotional Intelligence",
    slug: "emotional-intelligence",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Situational discernment regarding emotional self-awareness, empathy, and workplace composure.",
    subtopics: ["Recognising Emotions", "Empathy Based", "Situational EQ", "Self-awareness"],
  },
  {
    id: 24,
    priority: "least",
    icon: Share2,
    color: "#38bdf8",
    name: "Social Intelligence",
    slug: "social-intelligence",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Contextual problem-solving in interpersonal dynamics, civic duties, and ethical dilemmas.",
    subtopics: ["Socially Appropriate Responses", "Interpersonal Situations", "Group Behavior"],
  },
  {
    id: 25,
    priority: "least",
    icon: Type,
    color: "#a855f7",
    name: "Word Building",
    slug: "word-building",
    questions: "1",
    expectedMarks: "2 Marks",
    description: "Forming meaningful English words or identifying impossible words from a master letter repository.",
    subtopics: ["Form Words from Letters", "Find Words Within Words", "Meaningful Word Formation"],
  },
];

export const PRIORITY_CONFIG: Record<
  Priority,
  { label: string; badgeBg: string; badgeColor: string }
> = {
  "very-high": {
    label: "Core",
    badgeBg: "rgba(0, 113, 227, 0.1)",
    badgeColor: "var(--mac-blue)",
  },
  high: {
    label: "High",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-primary)",
  },
  medium: {
    label: "Medium",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-secondary)",
  },
  low: {
    label: "Low",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-secondary)",
  },
  least: {
    label: "Least",
    badgeBg: "var(--mac-surface-hover)",
    badgeColor: "var(--mac-text-tertiary)",
  },
};

export const CATEGORIES = [
  { id: "very-high", label: "Core", icon: Zap },
  { id: "high", label: "High", icon: TrendingUp },
  { id: "medium", label: "Medium", icon: CircleDot },
  { id: "low", label: "Low", icon: Filter },
  { id: "least", label: "Least", icon: Shapes },
] as const;

export type CategoryId = typeof CATEGORIES[number]["id"];

export const PRACTICE_MODES = [
  {
    key: "concept",
    title: "PYQ",
    sub: "Previous year Qs",
    mode: "concept",
    icon: FileQuestion,
    questions: "50 Qs",
    color: "#0d9488",
    gradient: "linear-gradient(135deg, #e6f7f2 0%, #d4f3eb 100%)",
    gradientDark: "linear-gradient(135deg, rgba(13, 148, 136, 0.2) 0%, rgba(13, 148, 136, 0.08) 100%)",
    border: "rgba(13, 148, 136, 0.22)",
    borderDark: "rgba(13, 148, 136, 0.35)",
    shadow: "0 2px 8px rgba(13, 148, 136, 0.08)",
  },
  {
    key: "formula",
    title: "CareerWill",
    sub: "Core formulas",
    mode: "formula",
    icon: BookOpenCheck,
    questions: "35 Qs",
    color: "#2563eb",
    gradient: "linear-gradient(135deg, #edf4fe 0%, #dbeafe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(37, 99, 235, 0.2) 0%, rgba(37, 99, 235, 0.08) 100%)",
    border: "rgba(37, 99, 235, 0.22)",
    borderDark: "rgba(37, 99, 235, 0.35)",
    shadow: "0 2px 8px rgba(37, 99, 235, 0.08)",
  },
  {
    key: "mixed",
    title: "PW",
    sub: "Mixed practice",
    mode: "mixed",
    icon: Shuffle,
    questions: "40 Qs",
    color: "#4f46e5",
    gradient: "linear-gradient(135deg, #f1f3fd 0%, #e0e7ff 100%)",
    gradientDark: "linear-gradient(135deg, rgba(79, 70, 229, 0.2) 0%, rgba(79, 70, 229, 0.08) 100%)",
    border: "rgba(79, 70, 229, 0.22)",
    borderDark: "rgba(79, 70, 229, 0.35)",
    shadow: "0 2px 8px rgba(79, 70, 229, 0.08)",
  },
  {
    key: "ai-challenge",
    title: "Selection Way",
    sub: "Speed test",
    mode: "ai-challenge",
    icon: Zap,
    questions: "25 Qs",
    color: "#7c3aed",
    gradient: "linear-gradient(135deg, #f7f2fe 0%, #ede9fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(124, 58, 237, 0.2) 0%, rgba(124, 58, 237, 0.08) 100%)",
    border: "rgba(124, 58, 237, 0.22)",
    borderDark: "rgba(124, 58, 237, 0.35)",
    shadow: "0 2px 8px rgba(124, 58, 237, 0.08)",
  },
  {
    key: "easy",
    title: "Topic Mix",
    sub: "Foundation easy",
    mode: "easy",
    icon: Compass,
    questions: "30 Qs",
    color: "#0284c7",
    gradient: "linear-gradient(135deg, #edf9ff 0%, #e0f2fe 100%)",
    gradientDark: "linear-gradient(135deg, rgba(2, 132, 199, 0.2) 0%, rgba(2, 132, 199, 0.08) 100%)",
    border: "rgba(2, 132, 199, 0.22)",
    borderDark: "rgba(2, 132, 199, 0.35)",
    shadow: "0 2px 8px rgba(2, 132, 199, 0.08)",
  },
  {
    key: "hard",
    title: "Tier 2",
    sub: "Advanced level",
    mode: "hard",
    icon: Flame,
    questions: "20 Qs",
    color: "#e11d48",
    gradient: "linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%)",
    gradientDark: "linear-gradient(135deg, rgba(225, 29, 72, 0.2) 0%, rgba(225, 29, 72, 0.08) 100%)",
    border: "rgba(225, 29, 72, 0.22)",
    borderDark: "rgba(225, 29, 72, 0.35)",
    shadow: "0 2px 8px rgba(225, 29, 72, 0.08)",
  },
] as const;