export const QUIZ_MODES = ["PYQ", "CareerWill", "PW", "Selection Way", "Topic Mix", "Tier 2"];
export const MENSURATION_QUIZ_MODES = ["PYQ", "CareerWill", "Selection Way", "Tier 2"];
export const SYNONYMS_QUIZ_MODES = [...QUIZ_MODES, "Study Mode"];

export const QUIZ_TREE: Record<string, { label: string; topics: Record<string, { label: string; quizzes: string[] }> }> = {
  mathematics: {
    label: "Mathematics",
    topics: {
      algebra: { label: "Algebra", quizzes: QUIZ_MODES },
      geometry: { label: "Geometry", quizzes: QUIZ_MODES },
      mensuration: { label: "Mensuration", quizzes: MENSURATION_QUIZ_MODES },
      trigonometry: { label: "Trigonometry", quizzes: QUIZ_MODES },
      "number-system": { label: "Number System", quizzes: QUIZ_MODES },
      "statistics-probability": { label: "Statistics & Probability", quizzes: QUIZ_MODES },
      averages: { label: "Averages", quizzes: QUIZ_MODES },
      discount: { label: "Discount", quizzes: QUIZ_MODES },
      interest: { label: "Interest", quizzes: QUIZ_MODES },
      "mixture-and-alligation": { label: "Mixture & Alligation", quizzes: QUIZ_MODES },
      partnership: { label: "Partnership", quizzes: QUIZ_MODES },
      percentages: { label: "Percentages", quizzes: QUIZ_MODES },
      "profit-and-loss": { label: "Profit & Loss", quizzes: QUIZ_MODES },
      "ratio-and-proportion": { label: "Ratio & Proportion", quizzes: QUIZ_MODES },
      "square-roots": { label: "Square Roots", quizzes: QUIZ_MODES },
      "time-and-distance": { label: "Time & Distance", quizzes: QUIZ_MODES },
      "time-and-work": { label: "Time & Work", quizzes: QUIZ_MODES },
    },
  },
  reasoning: {
    label: "Reasoning",
    topics: {
      analogy: { label: "Analogy", quizzes: QUIZ_MODES },
      "blood-relations": { label: "Blood Relations", quizzes: QUIZ_MODES },
      "classification-odd-one-out": { label: "Classification (Odd One Out)", quizzes: QUIZ_MODES },
      "coding-decoding": { label: "Coding & Decoding", quizzes: QUIZ_MODES },
      "cube-dice": { label: "Cube & Dice", quizzes: QUIZ_MODES },
      "direction-distance": { label: "Direction & Distance", quizzes: QUIZ_MODES },
      "emotional-intelligence": { label: "Emotional Intelligence", quizzes: QUIZ_MODES },
      inequalities: { label: "Inequalities", quizzes: QUIZ_MODES },
      "logical-sequence-of-words": { label: "Logical Sequence of Words", quizzes: QUIZ_MODES },
      "mathematical-symbolic-operations": { label: "Mathematical & Symbolic Operations", quizzes: QUIZ_MODES },
      matrix: { label: "Matrix", quizzes: QUIZ_MODES },
      "mirror-water-image": { label: "Mirror & Water Image", quizzes: QUIZ_MODES },
      "non-verbal-figures": { label: "Non-Verbal Figures", quizzes: QUIZ_MODES },
      "order-ranking": { label: "Order & Ranking", quizzes: QUIZ_MODES },
      "paper-folding-cutting": { label: "Paper Folding & Cutting", quizzes: QUIZ_MODES },
      "problem-solving-critical-thinking": { label: "Problem Solving & Critical Thinking", quizzes: QUIZ_MODES },
      "puzzle-seating-arrangement": { label: "Puzzle & Seating Arrangement", quizzes: QUIZ_MODES },
      series: { label: "Series", quizzes: QUIZ_MODES },
      "social-intelligence": { label: "Social Intelligence", quizzes: QUIZ_MODES },
      "statement-arguments": { label: "Statement & Arguments", quizzes: QUIZ_MODES },
      "statement-assumptions": { label: "Statement & Assumptions", quizzes: QUIZ_MODES },
      "statement-conclusion": { label: "Statement & Conclusion", quizzes: QUIZ_MODES },
      "syllogism-inferences": { label: "Syllogism & Inferences", quizzes: QUIZ_MODES },
      "venn-diagram": { label: "Venn Diagram", quizzes: QUIZ_MODES },
      "word-building": { label: "Word Building", quizzes: QUIZ_MODES },
    },
  },
  english: {
    label: "English",
    topics: {
      "active-passive-voice": { label: "Active & Passive Voice", quizzes: QUIZ_MODES },
      articles: { label: "Articles", quizzes: QUIZ_MODES },
      "cloze-test": { label: "Cloze Test", quizzes: QUIZ_MODES },
      conjunctions: { label: "Conjunctions", quizzes: QUIZ_MODES },
      "direct-indirect-narration": { label: "Direct & Indirect Narration", quizzes: QUIZ_MODES },
      "fill-in-the-blanks": { label: "Fill In The Blanks", quizzes: QUIZ_MODES },
      "homonyms-homophones": { label: "Homonyms & Homophones", quizzes: QUIZ_MODES },
      "idioms-phrases": { label: "Idioms & Phrases", quizzes: QUIZ_MODES },
      modifiers: { label: "Modifiers", quizzes: QUIZ_MODES },
      "one-word-substitution": { label: "One Word Substitution", quizzes: SYNONYMS_QUIZ_MODES },
      "para-jumbles": { label: "Para Jumbles", quizzes: QUIZ_MODES },
      "para-sentence-completion": { label: "Para / Sentence Completion", quizzes: QUIZ_MODES },
      parallelism: { label: "Parallelism", quizzes: QUIZ_MODES },
      prepositions: { label: "Prepositions", quizzes: QUIZ_MODES },
      pronouns: { label: "Pronouns", quizzes: QUIZ_MODES },
      "reading-comprehension": { label: "Reading Comprehension", quizzes: QUIZ_MODES },
      "sentence-correction-improvement": { label: "Sentence Correction / Improvement", quizzes: QUIZ_MODES },
      "sentence-structure": { label: "Sentence Structure", quizzes: QUIZ_MODES },
      "spelling-misspelled-words": { label: "Spelling / Misspelled Words", quizzes: QUIZ_MODES },
      "spot-the-error-error-detection": { label: "Spot the Error / Error Detection", quizzes: QUIZ_MODES },
      "subject-verb-agreement": { label: "Subject-Verb Agreement", quizzes: QUIZ_MODES },
      "synonyms-antonyms": { label: "Synonyms & Antonyms", quizzes: SYNONYMS_QUIZ_MODES },
      tenses: { label: "Tenses", quizzes: QUIZ_MODES },
    },
  },
  "general-awareness": {
    label: "General Awareness",
    topics: {
      "current-affairs": { label: "Current Affairs", quizzes: QUIZ_MODES },
      economics: { label: "Economics", quizzes: QUIZ_MODES },
      "general-science": { label: "General Science", quizzes: QUIZ_MODES },
      geography: { label: "Geography", quizzes: QUIZ_MODES },
      history: { label: "History", quizzes: QUIZ_MODES },
      polity: { label: "Polity", quizzes: QUIZ_MODES },
      "static-gk": { label: "Static GK", quizzes: QUIZ_MODES },
    },
  },
};

export const SUBJECT_TOPICS: Record<string, string[]> = {
  Mathematics: ["Number System", "Arithmetic", "Algebra", "Geometry", "Mensuration", "Trigonometry", "Statistics & Probability"],
  Reasoning: [
    "Coding & Decoding", "Syllogism & Inferences", "Puzzle & Seating Arrangement", "Series", "Analogy",
    "Classification (Odd One Out)", "Blood Relations", "Direction & Distance", "Venn Diagram", "Inequalities",
    "Mathematical & Symbolic Operations", "Order & Ranking", "Statement & Conclusion", "Statement & Assumptions",
    "Statement & Arguments", "Problem Solving & Critical Thinking", "Non-Verbal Figures", "Paper Folding & Cutting",
    "Mirror & Water Image", "Cube & Dice", "Matrix", "Logical Sequence of Words", "Emotional Intelligence",
    "Social Intelligence", "Word Building",
  ],
  English: [
    "Synonyms & Antonyms", "Homonyms & Homophones", "One Word Substitution", "Idioms & Phrases", "Spelling / Misspelled Words",
    "Active & Passive Voice", "Direct & Indirect Narration", "Subject-Verb Agreement", "Tenses", "Articles", "Prepositions",
    "Conjunctions", "Modifiers", "Pronouns", "Sentence Structure", "Parallelism", "Spot the Error / Error Detection",
    "Sentence Correction / Improvement", "Fill in the Blanks", "Cloze Test", "Reading Comprehension", "Para-Jumbles",
    "Para / Sentence Completion",
  ],
  "General Awareness": ["History", "Polity", "Geography", "Economics", "General Science", "Current Affairs", "Static GK"],
};
