export const SUBJECT_TOPICS: Record<string, string[]> = {
  Reasoning: [
    "Analogy",
    "Alphabet Test",
    "Assertion and Reason",
    "Coding-Decoding",
    "Data Sufficiency",
    "Direction Sense",
    "Embedded Figures",
    "Inequality",
    "Input Output",
    "Logical Sequence of Words",
    "Mathematical Operations",
    "Mirror Images",
    "Missing Number",
    "Odd One Out",
    "Order and Ranking",
    "Paper Cutting",
    "Water Images",
    "Classification",
    "Cause and Effect",
    "Clock and Calendar",
    "Dice and Cube",
    "Venn Diagrams",
    "Puzzle",
    "Seating Arrangement",
    "Series",
    "Blood Relations",
    "Paper Folding",
    "Syllogism",
    "Statement Conclusions",
    "Statement and Argument",
    "Statement and Assumption",
    "Statement and Conclusion",
    "Mirror and Water Images",
  ],
  Mathematics: [
    "Number System",
    "HCF and LCM",
    "Fractions and Decimals",
    "Percentage",
    "Ratio Proportion",
    "Profit Loss",
    "Simple Interest",
    "Compound Interest",
    "Discount",
    "Time Speed Distance",
    "Time Work",
    "Mensuration 2D",
    "Mensuration 3D",
    "Algebra",
    "Linear Equations",
    "Quadratic Equations",
    "Polynomials",
    "Sequences and Series",
    "Permutation and Combination",
    "Probability",
    "Statistics",
    "Geometry",
    "Coordinate Geometry",
    "Trigonometry",
    "Logarithms",
    "Matrices and Determinants",
  ],
  English: [
    "Synonyms",
    "Antonyms",
    "One Word Substitution",
    "Idioms Phrases",
    "Phrasal Verbs",
    "Vocabulary",
    "Error Spotting",
    "Sentence Improvement",
    "Grammar",
    "Active & Passive Voice",
    "Direct Indirect",
    "Para Jumbles",
    "Cloze Test",
    "Reading Comprehension",
    "Fill in the Blanks",
    "Sentence Completion",
    "Spellings",
  ],
  "General Awareness": [
    "History",
    "Geography",
    "Polity",
    "Economy",
    "Science",
    "Environment",
    "Current Affairs",
    "Static GK",
    "Sports",
    "Awards and Honors",
    "Books and Authors",
    "Important Dates",
    "Inventions and Discoveries",
    "International Organizations",
    "Capitals and Currencies",
    "National Parks",
    "Science and Technology",
  ],
};
