"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { fetchBattleRivalry, fetchBattleSocial, respondBattleFriendRequest, setBattleFavorite } from "@/lib/api/battleSocialApi";
import { getSocket } from "@/lib/socket";
type Player = { userId: string; displayName: string; online: boolean; favorite: boolean; season: { rating: number; tier: string } | null; lastPlayedAt?: string };
export default function BattleSocialPage() {
  const [data, setData] = useState<any>(null), [rivalry, setRivalry] = useState<any>(null), [error, setError] = useState("");
  const load = () => void fetchBattleSocial().then(setData).catch(() => setError("Could not load Battle Social.")); useEffect(load, []);
  const respond = async (id: string, action: "accept" | "decline") => { await respondBattleFriendRequest(id, action); load(); };
  const favorite = async (player: Player) => { await setBattleFavorite(player.userId, !player.favorite); load(); };
  const challenge = (player: Player) => { getSocket().emit("battle:challengeUser", { targetUserId: player.userId, subject: "mathematics", topic: "all", questionCount: 10 }); };
  const list = (title: string, players: Player[], actions = true) => <section className="mt-7"><h2 className="text-lg font-black">{title}</h2><div className="mt-2 space-y-2">{players.length ? players.map((player) => <div key={player.userId} className="flex items-center gap-3 rounded-xl bg-white p-3 shadow-sm"><span>{player.online ? "🟢" : "⚪"}</span><div className="min-w-0 flex-1"><div className="font-bold">{player.displayName}</div><div className="text-xs text-slate-500">{player.season ? `${player.season.tier} · ${player.season.rating}` : "No season rank"}{player.lastPlayedAt ? ` · Last played ${new Date(player.lastPlayedAt).toLocaleDateString()}` : ""}</div></div>{actions && <><button onClick={() => challenge(player)} className="rounded bg-violet-700 px-2 py-1 text-xs font-bold text-white">Challenge</button><button onClick={() => void favorite(player)} className="text-lg">{player.favorite ? "★" : "☆"}</button></>}</div>) : <p className="text-sm text-slate-500">None yet.</p>}</div></section>;
  if (error) return <main className="p-6 text-rose-600">{error}</main>; if (!data) return <main className="p-6 text-slate-500">Loading Battle Social…</main>;
  return <main className="mx-auto min-h-dvh max-w-2xl bg-slate-50 p-4 text-slate-900"><Link href="/battle" className="text-sm font-semibold text-violet-700">← Back to Battle</Link><h1 className="mt-4 text-3xl font-black">Battle Social</h1>{data.requests.length > 0 && <section className="mt-6"><h2 className="text-lg font-black">Friend Requests</h2>{data.requests.map((player: Player) => <div key={player.userId} className="mt-2 flex items-center justify-between rounded-xl bg-white p-3"><span className="font-bold">{player.displayName}</span><span className="flex gap-2"><button onClick={() => void respond(player.userId, "accept")} className="rounded bg-violet-700 px-3 py-1 text-sm text-white">Accept</button><button onClick={() => void respond(player.userId, "decline")} className="rounded border px-3 py-1 text-sm">Decline</button></span></div>)}</section>}{list("Online Friends", data.friends.filter((player: Player) => player.online))}{list("Favorites", data.favorites)}{list("Recent Opponents", data.recentOpponents)}{rivalry && <div className="mt-5 rounded-xl bg-white p-4"><b>Rivalry</b><p>{rivalry.total} battles · {rivalry.wins} wins · {rivalry.losses} losses · {rivalry.draws} draws</p></div>}</main>;
}
